// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTo978JyhZ-_2IgG3mQ9IqtQ-uRus3wIg',
    appId: '1:697289806380:android:8cdcdf522605f14001f789',
    messagingSenderId: '697289806380',
    projectId: 'hayat-423512',
    storageBucket: 'hayat-423512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdw6CuZkT2xi8-Nn89vsocNxYvIcoC_K8',
    appId: '1:697289806380:ios:55e5d759c361960701f789',
    messagingSenderId: '697289806380',
    projectId: 'hayat-423512',
    storageBucket: 'hayat-423512.appspot.com',
    androidClientId: '697289806380-vlint868chi1nctdosm67ej6ha1b4b3m.apps.googleusercontent.com',
    iosClientId: '697289806380-nt205ct6lof85rdb1ja6557cr29e8p4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.hayat',
  );
}
